clinic_project/clinic/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views, dr_views

app_name = 'clinic'
# "{% url 'polls:vote' question.id %}"s change_doctor
urlpatterns = [
    # reception url
    path('reception/home', views.Home, name='Reception_Home'),
    path('reception/register',views.register, name='register'),
    path('reception/edit_card',views.editcard, name='edit_card'),
    path('reception/card',views.card, name='card'),
    path('reception/fetch_data',views.fetch_data, name='fetch_data'),
    path('reception/associate',views.associate, name='associate'),
    path('reception/assign_doctor',views.assign_doctor,name='assign_doctor'),
    path('reception/change_doctor',views.change_doctor,name='change_doctor'),
    path('reception/searchID',views.searchID,name='searchID'),
    path('reception/updatecard',views.updatecard,name='updatecard'),
    # doctor url
    path('doctor/home',dr_views.home,name='doctor_home'),
    path('doctor/room',dr_views.room,name='room'),
    path('doctor/checked',dr_views.patient_checked,name="p_checked"),
    path('doctor/getData',dr_views.getData,name="getData"),
    path('doctor/getPData',dr_views.getPData,name='getPData'),
    # getDrug
    path('doctor/getDrug',dr_views.getDrug,name='getDrug'),

]

clinic_project/ssms/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clinic/',include('clinic.urls')),
    path('accounts/',include('django.contrib.auth.urls'), name='login'),
    path('', views.auth, name='auth')
]

clinic_project/clinic/models.py
from django.db import models

# Create your models here.

clinic_project/clinic/views.py
from django.shortcuts import *
from  django.contrib.auth.decorators import *
from ssms_model.models import *
import datetime
from django.http import JsonResponse

# Create your views here.
@login_required(redirect_field_name="login")
def Home(request):
    return render(request,'reception/index.html')

@login_required(redirect_field_name="login")
def register(request):
    date = datetime.date.today()
    todays_patient = Priscriptions.objects.\
            select_related('student').\
                filter(
                            
                            examination_date__isnull=True,
                            registration__registration_date=date
                               )
    
    doctors = Doctors.objects.all()

    context={
        'patient':todays_patient,
        'doctors':doctors
    }
    
    return render(request,'reception/register.html',context)

@login_required(redirect_field_name="login")
def editcard(request):
    context={}
    return render(request,'reception/card_edit.html',context)

@login_required(redirect_field_name="login")
def card(request):
    context={}
    return render(request,'reception/card.html',context)

@login_required(redirect_field_name="login")
def fetch_data(request):
    context={  
        }
    try:
        data = Students.objects.get(barcode = request.POST.get('data'))
    except:
        context={
            'associate':'Student id should be associated! please use the ⇓ Button to associate.',
            'style':'danger',
            'barcode':request.POST.get('data'),
        }
        return render(request,'reception/associate.html',context)
    else:
        date = datetime.date.today()
        cards_asso = get_object_or_404(Student_cards, student=data.id)
        cards = get_object_or_404(Card, id=cards_asso.card_id)
        years = get_object_or_404(Years, id=data.entry_batch)
        #get free doctors
        doctors = Doctors.objects.all()
        list_doctors = {
        }
        check_prisc = Priscriptions.objects.filter(
            examination_date__isnull=True,
            registration__registration_date=date
        )[0]
        if check_prisc:
            context={
            'data':data,
            'cards':cards,
            'year':years,
            'allready_assigned':'check_prisc.id',
            'msg':'Allready Assigned'
                }
            return render(request,'reception/table.html',context)
        for doc in doctors:
           counts = Priscriptions.objects.\
                filter(
                            doctor_id=doc.id,
                            examination_date__isnull=True,
                            registration__registration_date=date
                               ).\
                                count()
           
           personal_ = Employees.objects.get(pk=doc.employee_id)
           list_doctors[personal_.full_name]=[counts,doc.id]
        context={
            'data':data,
            'cards':cards,
            'year':years,
            'doctors':list_doctors
        }
    return render(request,'reception/table.html',context)

@login_required(redirect_field_name="login")
def associate(request):
    msg = ''
    try:
        data = Students.objects.get(id_number = request.POST.get('code'))
    except  Students.DoesNotExist:
        context={
            'associate':'No student In the Database! Please Ask Help From The Administrator.',
            'style':'danger',
            }
        return render(request,'reception/associate.html',context)
    else:
        date = datetime.date.today()
        regis = Registration(
            registration_date = date,
            student_id=data.id,
            reception_id= request.user.id,  #api data
            employee_id=None
            )
        data.barcode = request.POST.get('code')
        data.save(update_fields=['barcode'])
        ent_batch = str(data.entry_batch)+'-'
        cards = Card.objects.filter(number__startswith=ent_batch).order_by('-number')
        if not cards:
            date = datetime.date.today()
            e_bath = str(data.entry_batch)+'-'+str(1)

            card_done = Card(number=e_bath, location_id=date.year)
            card_done.save()

            stude = Student_cards(
                date=date, 
                card_id=card_done.id, 
                student_id=data.id
                )
            stude.save()
        else:
            card_ = cards[0].number.split('-')
            incr = int(card_[1])+1
            numb = card_[0]+'-'+str(incr)
            date = datetime.date.today()
            
            card_done = Card(number=numb, location_id=date.year)
            card_done.save()


            stude = Student_cards(
                date=date, 
                card_id=card_done.id, 
                student_id=data.id
                )
            stude.save()
        msg = 'Associated successfully.'
    context={
            'success':msg,
            'style':'success',
            }
    return render(request,'reception/associate.html',context)


@login_required(redirect_field_name='login')
def assign_doctor(request):
    doctor_id = request.POST.get('doc_id')
    id_number = request.POST.get('id_number')
    
    register_id = Registration.objects.filter(
        student_id__id_number=id_number
    )[0]
    priscr = Priscriptions(
                            doctor_id=doctor_id, 
                            student_id=register_id.student_id, 
                            registration_id=register_id.id
                            )
    priscr.save()
    context={
            'success':'Doctor Assigned',
            'style':'success',
            }
    return render(request, 'reception/msg.html',context)

@login_required(redirect_field_name="login")
def change_doctor(request):
    doc_id = request.POST.get('doc_id')
    stud_id = request.POST.get('stud_id')
    change_doc_id = request.POST.get('change_doc_id')
    date = datetime.date.today()
    changedoc = Priscriptions.objects.filter(
                            doctor_id=change_doc_id, 
                            student_id=stud_id, 
                            registration__registration_date=date
                            )[0]

    changedoc.doctor_id = doc_id
    changedoc.save(update_fields=['doctor_id'])

    data = {
        'success':"Doctor Changed!"
        }
    return JsonResponse(data)

@login_required(redirect_field_name='login')
def searchID(request):
    idnumber = request.POST.get('id_number')
    student = Students.objects.filter(
        id_number = idnumber
    )
    
    context={'student':None}
    if student:
        student=student[0]
        card = Student_cards.objects.get(student_id=student.id)
        context = {
            'student':student,
            'card':card
            }
    return render(request,'reception/editcard.html',context)

@login_required(redirect_field_name='login')
def updatecard(request):
    number = request.POST.get('number')
    location = request.POST.get('location')
    id = request.POST.get('id')

    card_update = Card.objects.get(pk=id)
    card_update.number=number
    card_update.location_id=location
    card_update.save(update_fields=['number','location_id'])

    data = {
        'success':"Card updated successfully!"
            }
    return JsonResponse(data)

clinic_project/clinic/templates/doctor/index.html
<!DOCTYPE html>
<html lang="en">

{% include "layout/header.html" %}

<body class="hold-transition sidebar-mini layout-fixed" >
    <div class="wrapper">
        
{% include "layout/nav.html" %}
{% include "layout/side.html" %}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">OPD</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">page</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
       



      
       


      </div><!-- /.container-fluid -->
    </section>
   
      

    <!-- /.content -->
  </div>
     









    </div>
</body>
{% include "layout/footer.html" %}

{% include "layout/footer_script.html" %}

</html>

clinic_project/clinic/templates/doctor/patientinfo.html
<div class="row">
    <div class="col-12 ">
        <div class="form-group row offset-1">
            <label for="druglist" class="col-sm-2 col-form-label">Full Name</label>
            <div class="col">
                <div class="form-control  col-sm-6">
        {{patients.student.personal_name}} {{patients.student.father_name}} {{patients.student.grand_father_name}}
            </div>
        </div>
        </div>
    </div>
<input type="hidden" name="priscription_id" value="{{patients.id}}">
    <div class="col-12">
        <div class="form-group row offset-1">
            <label for="druglist" class="col-sm-2 col-form-label">Disease Type</label>
            <div class="col ">
              <select name="disease_id" id="disease_id" class="form-control col-sm-6" >
                  <option value=""> --- -- select Disease -- ---</option>
                  {% for disease in diseases %}
                  <option value="{{disease.id}}">{{disease.name}}</option>
                  {% endfor %}
              </select>
            </div>
    </div>
    <div class="col-12" id="priscription_t">
            

            </div>
    </div>
</div>


    <div class="modal-body">
        <div class="modal-footer justify-content-between">
          <button id="bchecked" class="btn btn-success">Save changes</button>
        </div>
    </div>

clinic_project/clinic/templates/doctor/priscription.html
<div class="col">
    <table class="table table-striped table-hover table-bordered">
        <thead>
        <tr>
        <th>No</th><th>Category</th><th>Drug</th><th>Quantity</th><th colspan="3">Dosage</th><th>Remark</th></tr>
        </thead>
        <tbody>
        <tr>
        <td><label id="num" class="control-label">1</label></td><td>
            <select id="category_id" required name="category_id" class="form-control input-sm">
                
                {% if categorys_name.name == None %}
                <option selected value="">--- Choose Category ---</option>
                {% endif %}
                {% for category in categorys %}
                
                    {% if category.name == categorys_name.name %}
                        <option selected value="{{category.id}}">{{categorys_name.name}}</option>
                   {% else %}
                   <option value="{{category.id}}">{{ category.name  }}</option>
                    {% endif %}
                    
                
                {% endfor %}
            </select></td>
            <td>
            <select id="drug_id" required name="drug_id" class="form-control input-sm">
                <option value=""> -- Select Drug --</option>
                {% for drug in drugs %}
                <option value="{{drug.id}}"> {{drug.name}}</option>
                {% endfor %}
            </select></td>
            <td>
                <input data-type="number" type="number" class="form-control" id="quantity" name="quantity" required placeholder="Quantity">
            </td>
            <td>
                <select id="amount_id" name="amount_id" class="form-control input-sm" required>
                <option value="">none</option>
                {% for amount in amounts %}
                <option value="{{amount.id}}">{{amount.name}}</option>
                {% endfor %}
            </select></td>
                <td>
                <select id="type_id" name="type_id" required class="form-control input-sm">
                    <option value="">none</option>
                    {% for dosage_type in dosage_types %}
                    <option value="{{dosage_type.id}}">{{dosage_type.name}}</option>
                    {% endfor %}
                </select>
                </td>
                <td>
                <select id="frequency_id" required name="frequency_id" class="form-control input-sm">
                    <option value="">none</option>
                    {% for frequency in frequencys %}
                    <option value="{{frequency.id}}">{{frequency.name}}</option>
                    {% endfor %}
                </select>
                </td>
                <td><textarea data-type="textarea" cols="15" class="form-control" id="remark" name="remark" placeholder="Remark">
                </textarea>
                </td>
            </tr>
        </tbody>
        </table>
  </div>

clinic_project/clinic/templates/doctor/room.html
<!DOCTYPE html>
<html lang="en">

{% include "layout/header.html" %}

<body class="hold-transition sidebar-mini layout-fixed" >
    <div class="wrapper">
        
{% include "layout/nav.html" %}
{% include "layout/side.html" %}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">OPD</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Room</a></li>
              <li class="breadcrumb-item active">page</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
       

          
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Patient Information</h3>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <table id="table" class="table table-bordered table-striped table-hover">
              <thead>
              <tr>
                <th>#</th>
                <th>Student</th>
                <th>Id Number</th>
                <th>Action</th>
              </tr>
              </thead>
              <tbody>
            {% for patient in patients %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                  {{ patient.student.personal_name }}
                  {{ patient.student.father_name }}
                  {{ patient.student.grand_father_name }}
                </td>
                <td>{{ patient.student.id_number }}</td>
                <td>
                  {% if patient.examination_date != None %}
                    <span>Treated</span>
                    <a class="btn btn-info" id="view_opd_p" data-id="{{patient.student.id}}" 
                      data-backdrop='static' data-keyboard='false' data-toggle="modal" data-target="#opd_view" href="#">
                    Add Priscribe
                  </a>
                  {% else %}
                  <a class="btn btn-info" id="view_opd_p" data-id="{{patient.student.id}}" 
                      data-backdrop='static' data-keyboard='false' data-toggle="modal" data-target="#opd_view" href="#">
                    Priscribe
                  </a>
                  {% endif %}
                  <a class="btn btn-info" id="view_opd_r" data-id="{{patient.student.id}}" 
                      data-backdrop='static' data-keyboard='false' data-toggle="modal" data-target="#opd_view" href="#">
                    Refer
                  </a>
                  <a class="btn btn-info" id="view_opd_l" data-id="{{patient.student.id}}" 
                      data-backdrop='static' data-keyboard='false' data-toggle="modal" data-target="#opd_view" href="#">
                    Laboratory
                  </a>
                </td>
              </tr>
            {% endfor %}
              </tbody>
              
            </table>
          </div>
          <!-- /.card-body -->
        </div>
       


      </div><!-- /.container-fluid -->
    </section>
   
      

    <!-- /.content -->
  </div>
     





  <div class="modal fade" id="opd_view">
    <div class="modal-dialog modal-xl">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Diagnose Patient</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="{% url 'clinic:p_checked' %}" method="post">
          {% csrf_token %}
        <div  id="viewdata">
          
        </div>
        
      </form>
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
  </div>



    </div>
</body>
{% include "layout/footer.html" %}

{% include "layout/footer_script.html" %}

</html>