clinic_project/clinic/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views, dr_views

app_name = 'clinic'
# "{% url 'polls:vote' question.id %}"s change_doctor
urlpatterns = [
    # reception url
    path('reception/home', views.Home, name='Reception_Home'),
    path('reception/register',views.register, name='register'),
    path('reception/edit_card',views.editcard, name='edit_card'),
    path('reception/card',views.card, name='card'),
    path('reception/fetch_data',views.fetch_data, name='fetch_data'),
    path('reception/associate',views.associate, name='associate'),
    path('reception/assign_doctor',views.assign_doctor,name='assign_doctor'),
    path('reception/change_doctor',views.change_doctor,name='change_doctor'),
    path('reception/searchID',views.searchID,name='searchID'),
    path('reception/updatecard',views.updatecard,name='updatecard'),
    # doctor url
    path('doctor/home',dr_views.home,name='doctor_home'),
    path('doctor/room',dr_views.room,name='room'),
    path('doctor/checked',dr_views.patient_checked,name="p_checked"),
    path('doctor/getData',dr_views.getData,name="getData"),
    path('doctor/getPData',dr_views.getPData,name='getPData'),
    # getDrug
    path('doctor/getDrug',dr_views.getDrug,name='getDrug'),

]

clinic_project/ssms/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clinic/',include('clinic.urls')),
    path('accounts/',include('django.contrib.auth.urls'), name='login'),
    path('', views.auth, name='auth')
]

clinic_project/clinic/models.py
from django.db import models

# Create your models here.

clinic_project/clinic/views.py
from django.shortcuts import *
from  django.contrib.auth.decorators import *
from ssms_model.models import *
import datetime
from django.http import JsonResponse

# Create your views here.
@login_required(redirect_field_name="login")
def Home(request):
    return render(request,'reception/index.html')

@login_required(redirect_field_name="login")
def register(request):
    date = datetime.date.today()
    todays_patient = Priscriptions.objects.\
            select_related('student').\
                filter(
                            
                            examination_date__isnull=True,
                            registration__registration_date=date
                               )
    
    doctors = Doctors.objects.all()

    context={
        'patient':todays_patient,
        'doctors':doctors
    }
    
    return render(request,'reception/register.html',context)

@login_required(redirect_field_name="login")
def editcard(request):
    context={}
    return render(request,'reception/card_edit.html',context)

@login_required(redirect_field_name="login")
def card(request):
    context={}
    return render(request,'reception/card.html',context)

@login_required(redirect_field_name="login")
def fetch_data(request):
    context={  
        }
    try:
        data = Students.objects.get(barcode = request.POST.get('data'))
    except:
        context={
            'associate':'Student id should be associated! please use the ⇓ Button to associate.',
            'style':'danger',
            'barcode':request.POST.get('data'),
        }
        return render(request,'reception/associate.html',context)
    else:
        date = datetime.date.today()
        cards_asso = get_object_or_404(Student_cards, student=data.id)
        cards = get_object_or_404(Card, id=cards_asso.card_id)
        years = get_object_or_404(Years, id=data.entry_batch)
        #get free doctors
        doctors = Doctors.objects.all()
        list_doctors = {
        }
        check_prisc = Priscriptions.objects.filter(
            examination_date__isnull=True,
            registration__registration_date=date
        )[0]
        if check_prisc:
            context={
            'data':data,
            'cards':cards,
            'year':years,
            'allready_assigned':'check_prisc.id',
            'msg':'Allready Assigned'
                }
            return render(request,'reception/table.html',context)
        for doc in doctors:
           counts = Priscriptions.objects.\
                filter(
                            doctor_id=doc.id,
                            examination_date__isnull=True,
                            registration__registration_date=date
                               ).\
                                count()
           
           personal_ = Employees.objects.get(pk=doc.employee_id)
           list_doctors[personal_.full_name]=[counts,doc.id]
        context={
            'data':data,
            'cards':cards,
            'year':years,
            'doctors':list_doctors
        }
    return render(request,'reception/table.html',context)

@login_required(redirect_field_name="login")
def associate(request):
    msg = ''
    try:
        data = Students.objects.get(id_number = request.POST.get('code'))
    except  Students.DoesNotExist:
        context={
            'associate':'No student In the Database! Please Ask Help From The Administrator.',
            'style':'danger',
            }
        return render(request,'reception/associate.html',context)
    else:
        date = datetime.date.today()
        regis = Registration(
            registration_date = date,
            student_id=data.id,
            reception_id= request.user.id,  #api data
            employee_id=None
            )
        data.barcode = request.POST.get('code')
        data.save(update_fields=['barcode'])
        ent_batch = str(data.entry_batch)+'-'
        cards = Card.objects.filter(number__startswith=ent_batch).order_by('-number')
        if not cards:
            date = datetime.date.today()
            e_bath = str(data.entry_batch)+'-'+str(1)

            card_done = Card(number=e_bath, location_id=date.year)
            card_done.save()

            stude = Student_cards(
                date=date, 
                card_id=card_done.id, 
                student_id=data.id
                )
            stude.save()
        else:
            card_ = cards[0].number.split('-')
            incr = int(card_[1])+1
            numb = card_[0]+'-'+str(incr)
            date = datetime.date.today()
            
            card_done = Card(number=numb, location_id=date.year)
            card_done.save()


            stude = Student_cards(
                date=date, 
                card_id=card_done.id, 
                student_id=data.id
                )
            stude.save()
        msg = 'Associated successfully.'
    context={
            'success':msg,
            'style':'success',
            }
    return render(request,'reception/associate.html',context)


@login_required(redirect_field_name='login')
def assign_doctor(request):
    doctor_id = request.POST.get('doc_id')
    id_number = request.POST.get('id_number')
    
    register_id = Registration.objects.filter(
        student_id__id_number=id_number
    )[0]
    priscr = Priscriptions(
                            doctor_id=doctor_id, 
                            student_id=register_id.student_id, 
                            registration_id=register_id.id
                            )
    priscr.save()
    context={
            'success':'Doctor Assigned',
            'style':'success',
            }
    return render(request, 'reception/msg.html',context)

@login_required(redirect_field_name="login")
def change_doctor(request):
    doc_id = request.POST.get('doc_id')
    stud_id = request.POST.get('stud_id')
    change_doc_id = request.POST.get('change_doc_id')
    date = datetime.date.today()
    changedoc = Priscriptions.objects.filter(
                            doctor_id=change_doc_id, 
                            student_id=stud_id, 
                            registration__registration_date=date
                            )[0]

    changedoc.doctor_id = doc_id
    changedoc.save(update_fields=['doctor_id'])

    data = {
        'success':"Doctor Changed!"
        }
    return JsonResponse(data)

@login_required(redirect_field_name='login')
def searchID(request):
    idnumber = request.POST.get('id_number')
    student = Students.objects.filter(
        id_number = idnumber
    )
    
    context={'student':None}
    if student:
        student=student[0]
        card = Student_cards.objects.get(student_id=student.id)
        context = {
            'student':student,
            'card':card
            }
    return render(request,'reception/editcard.html',context)

@login_required(redirect_field_name='login')
def updatecard(request):
    number = request.POST.get('number')
    location = request.POST.get('location')
    id = request.POST.get('id')

    card_update = Card.objects.get(pk=id)
    card_update.number=number
    card_update.location_id=location
    card_update.save(update_fields=['number','location_id'])

    data = {
        'success':"Card updated successfully!"
            }
    return JsonResponse(data)

clinic_project/clinic/templates/layout/footer.html
<footer class="main-footer">
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">ASTU</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.2.0
    </div>
  </footer>

clinic_project/clinic/templates/layout/footer_script.html
{% load static %}
<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- ChartJS -->
<script src="{% static 'plugins/chart.js/Chart.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'plugins/sparklines/sparkline.js' %}"></script>
<!-- JQVMap -->
<script src="{% static 'plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static 'plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- Summernote -->
<script src="{% static 'plugins/summernote/summernote-bs4.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- datatable -->
<script src="{% static 'plugins/datatables/jquery.dataTables.js' %}"></script>
<!-- AdminLTE App -->
 
<script src="{% static 'dist/js/adminlte.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
 <!-- datatable script -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
<!-- Select2 -->
<script src="{% static 'plugins/select2/js/select2.full.min.js' %}"></script>
<!-- Toastr -->
 <!-- SweetAlert2 -->
<script src="{% static 'plugins/sweetalert2/sweetalert2.min.js' %}"></script>
<script src="{% static 'plugins/toastr/toastr.min.js' %}"></script>
  <script>
 var Toast = Swal.mixin({
      toast: true,
      position: 'top-end',
      showConfirmButton: false,
      timer: 3000
    });
    //Initialize Select2 Elements
      $('.select2').select2({
        theme: 'bootstrap4'
      })

let code = "";
let reading = false;

document.addEventListener('keypress', e => {
  
  //usually scanners throw an 'Enter' key at the end of read
   if (e.keyCode === 13) {

          if(code.length > 10) {
            console.log(code);
            /// code ready to use                
            code = "";
         }
         
    } else {
        code += e.key; //while this is not an 'enter' it stores the every key            
    }

    //run a timeout of 200ms at the first read and clear everything
    if(!reading) {
        reading = true;

        setTimeout(() => {
          $.ajax({
            type: "POST",
            url: "{% url 'clinic:fetch_data' %}",
            data: {
              'csrfmiddlewaretoken':'{{ csrf_token }}',
              'data':code,
            },
            success: function(msg){
             $('#result').html(msg)
           }
          })
          code = "";
          reading = false
        }, 500);  //200 works fine for me but you can adjust it
    }
   
});

$('#table').DataTable( {
    
} );
$('#table1').DataTable({})

$(document).on('click','#associate',function(e){
        var code = $(this).data('barcode')
          $.ajax({
            type: "POST",
            url: "{% url 'clinic:associate' %}",
            data: {
              'csrfmiddlewaretoken':'{{ csrf_token }}',
              'code':code,
            },
            success: function(msg){
              $('#result').html(msg)
           }
          })
})
$(document).on('click','#assign_doc',function(e){
    var doc_id = $(this).data('doctor_id')
    var id_number = $(this).data('id_number')
    $.ajax({
            type: "POST",
            url: "{% url 'clinic:assign_doctor' %}",
            data: {
              'csrfmiddlewaretoken':'{{ csrf_token }}',
              'doc_id':doc_id,
              'id_number':id_number,
            },
            success: function(msg){
              $('#doc_asigned').html(msg)
           }
          })
})
$(document).on('change','#change_doc',function(){
  var doc_id = $(this).val()
  var stud_id = $(this).data('stud')
  var change_doc_id = $(this).data('changedoc')
  $.ajax({
            type: "POST",
            url: "{% url 'clinic:change_doctor' %}",
            data: {
              'csrfmiddlewaretoken':'{{ csrf_token }}',
              'doc_id':doc_id,
              'change_doc_id':change_doc_id,
              'stud_id':stud_id,
            },
            success: function(msg){
                toastr.success(msg.success)
              
              setTimeout(() => {
              location.reload();
              
              },700)
              
           }
        })
})

$(document).on('click','#search_card',function(){
  var id_number = $('#key_id_number').val()
  $.ajax({
            type: "POST",
            url: "{% url 'clinic:searchID' %}",
            data: {
              'csrfmiddlewaretoken':'{{ csrf_token }}',
              'id_number':id_number,
            },
            success: function(msg){
                // toastr.success(msg.success)
              $('#edit_card').html(msg)
              // setTimeout(() => {
              // location.reload();
              
              // },700)
              
           }
        })
})

$(document).on('click','#updatecard',function(){
  var number = $('#number').val()
  var location = $('#location').val()
  var id = $('#id').val()
      $.ajax({
          type: "POST",
            url: "{% url 'clinic:updatecard' %}",
            data: {
              'csrfmiddlewaretoken':'{{ csrf_token }}',
              'number':number,
              'location':location,
              'id':id
            },
            success: function(msg){
              toastr.success(msg.success)
              setTimeout(() => {
                document.location.reload();
              },700)
              
          }
  })
})

$(document).on('click','#view_opd_p',function(){

  var id = $(this).data('id')
  $.ajax({
    type:'POST',
    url:"{% url 'clinic:getData' %}",
    data:{
      'csrfmiddlewaretoken':'{{ csrf_token }}',
      'id':id
    },
    success:function(data){
      $('#viewdata').html(data)
    }
  })
})
$(document).on('change','#disease_id',function(){
  $.ajax({
    type:'POST',
    url:"{% url 'clinic:getPData' %}",
    data:{
      'csrfmiddlewaretoken':'{{ csrf_token }}',
    },
    success:function(data){
      $('#priscription_t').html(data)
    }
  })
})
$(document).on('change','#category_id',function(){
  var id = $(this).val()
  $.ajax({
    type:'POST',
    url:"{% url 'clinic:getDrug' %}",
    data:{
      'csrfmiddlewaretoken':'{{ csrf_token }}',
      'id':id
    },
    success:function(data){
      $('#priscription_t').html(data)
    }
  })
})
</script>

clinic_project/clinic/templates/layout/header.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clinic Home</title>
     <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static 'plugins/jqvmap/jqvmap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css' %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.min.css' %}">
  <!-- responsive.bootstrap4 -->
  <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
   <!-- Select2 -->
   <link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css' %}">
   <link rel="stylesheet" href="{% static 'plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css' %}">

   <link rel="stylesheet" href="{% static 'plugins/toastr/toastr.min.css' %}">


</head>

clinic_project/clinic/templates/layout/nav.html
{% load static %}
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item">
      {% if user.groups.all.0.name  == 'reception' %}
        <a class="nav-link" href="{% url 'clinic:Reception_Home' %}" role="button">
          Reception
          <i class="fas fa-home"></i>
        </a>
      {% elif user.groups.all.0.name  == "doctor" %}
        <a class="nav-link" href="{% url 'clinic:doctor_home' %}" role="button">
          OPD
          <i class="fas fa-home"></i>
        </a>
      {% endif %}
    </a>
    </li>
  </ul>
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <div class="user-panel pb-3 mb-3 d-flex">
              <img src="{% static 'dist/img/avatar.png' %}" 
              class="img-circle elevation-2" alt="User Image">
          </div>
        </a>
        
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">Manage Account</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-eye mr-2"></i> View Profile
          </a>
          <div class="dropdown-divider"></div>
          <form action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <button  class="dropdown-item">
              <i class="fas fa-lock mr-2"></i> Logout
            </button>
          </form>

        </div>
      </li>
    </ul>
  </nav>

clinic_project/clinic/templates/layout/side.html
{% load static %}
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    {% for group in user.groups.all %}
              {% if group.name  == 'reception' %}
    <a href="{% url 'clinic:Reception_Home' %}" class="brand-link pl-2 ">

              {% elif group.name  == 'doctor' %}

    <a href="{% url 'clinic:doctor_home' %}" class="brand-link pl-2 ">
    
              {% endif %}
              
            {% endfor  %}
          
      <img src="{% static 'dist/img/astu.jpg' %}" alt="AdminLTE Logo" 
      class="brand-image img-circle elevation-3 " style="opacity: .8">
      <span class="brand-text font-weight-light">SSMS</span>
    </a>
  

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{% static 'dist/img/avatar.png' %}" 
          class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{{request.user.first_name}}, {{request.user.last_name}} </a>
        </div>
      </div>


      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column nav-child-indent" 
        data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item menu-open">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Main Menu
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              {% for group in user.groups.all %}
              {% if group.name  == 'reception' %}
                <li class="nav-item">
                  <a href="{% url 'clinic:register' %}" class="nav-link {% if request.path == '/clinic/reception/register' %} active {% endif %}">
                    <i class="far fa-user nav-icon"></i>
                    <p>Register</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'clinic:card' %}" class="nav-link {% if request.path == '/clinic/reception/card' %} active {% endif %}">
                    <i class="far fa-address-card nav-icon"></i>
                    <p>Card</p>
                  </a>
                </li>
              {% elif group.name  == 'doctor' %}
                <li class="nav-item">
                  <a href="{% url 'clinic:room' %}"
                   class="nav-link {% if request.path == '/clinic/doctor/room' %} active {% endif %}">
                    <i class="far fa-user nav-icon"></i>
                    <p>Examination</p>
                  </a>
                </li>
              {% endif %}
              
            {% endfor  %}
            </ul>
          </li>
          
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>